### ISSUE TITLE
backend with blank: one directory generated which should not be

### ISSUE THREAD

**Issue by klauspdoll** [molpro/sjef#201]
as a follow up from #58 :

sjef version 7caa37955a

Use the script from https://github.com/molpro/sjef/blob/master/test/test_spaces.sh

with these changes:

```
diff test_spaces.sh test_spaces_klaus_blank.sh 
2,3c2,3
< molpro_command="/usr/local/bin/molpro"
< host=$(hostname)
---
> molpro_command="molpro"
> host=linux24
6,8c6,8
< work_directory="${TMPDIR:-/tmp}/sjef test spaces"
< cache="/tmp/${USER}/sjef test spaces/with spaces"
< project_name="project name containing spaces"
---
> work_directory="/tmp/sjefbla"
> cache="/tmp/doll/sjefblacache blank"
> project_name="blatest"

```

clean up /tmp before running the script, run:

```
sh test_spaces_klaus_blank.sh 
Working directory: /tmp/sjefbla
Remote cache: linux24:/tmp/doll/sjefblacache blank
Project name: blatest
Job number: 6083
Running, job number 6083 on backend testing-remote
Completed, job number 6083 on backend testing-remote
 !RHF STATE 1.1 Energy                 -2.855160477243
 !RHF STATE 1.1 Dipole moment           0.00000000     0.00000000     0.00000000
```

This looks all good. There is a  flaw that there is now a directory which should not be there:

```
ls -ltr /tmp/doll/sjefblacache/
total 0

```
probably because of
`cache="/tmp/doll/sjefblacache blank"`

**Comment by pjknowles** [comment]
OK, so the cache directory - which could be used simultaneously by several projects - should be removed if it becomes completely empty

**Comment by pjknowles** [comment]
Oh I see. That should be easy enough to find.

**Comment by pjknowles** [comment]
This was just because the test script tried needlessly to create the remote cache without taking care of escaping spaces. Fixed with https://github.com/molpro/sjef/pull/203

I don't think we need to go to the trouble of removing the top level cache directory.
