### ISSUE TITLE
remote shell commands: need to watch out for special characters

### ISSUE THREAD

**Issue by klauspdoll** [molpro/sjef#226]
I have a non-reproducible case , where sjef has a problem with commands sent to the remote backend, when e.g. the cache
contains special characters.

I have created a backend with:

```
    <backend name="withquestionmark"
             host="doll@XXX.XX.XX.XXX"
             cache="/SCR1/doll/a?"
             run_command="molpro {-n %n:1} {-m %m:100m} {-t %t}  {-G %G} "/>
    <backend name="withstar"
             host="doll@XXX.XX.XX.XXX"
             cache="/SCR1/doll/a*"
             run_command="molpro {-n %n:1} {-m %m:100m} {-t %t}  {-G %G} "/>
```

Logged in on the remote machine, I lclean up:
`rm -r /SCR1/doll/a*`
and then create:

```
mkdir /SCR1/doll/a*
mkdir /SCR1/doll/a\?
mkdir /SCR1/doll/a2
```

Note that already these commands are somewhat ambiguous. If you create first
`mkdir /SCR1/doll/a2`

then

`mkdir /SCR1/doll/a*`

fails with:

`mkdir /SCR1/doll/a*
mkdir: cannot create directory ‘/SCR1/doll/a*’: File exists`

When I now run an input, I obtain non-reproducibly (Molpro input file is irrelevant):

```
sjef run -b withquestionmark -f ~/Documents/molpro/test-remote-shell.molpro
Job number: 11130
```

and on the remote machine I have:
```

ls -ltR --time-style="+%Y-%m-%d %H:%M:%S" a?
a2:
total 0
drwxr-xr-x 2 doll user 130 2022-10-10 09:22:32 16634613613130276360

a2/16634613613130276360:
total 12
-rw-r--r-- 1 doll user 106 2022-10-10 09:22:32 1.inp
-rw-r--r-- 1 doll user   0 2022-10-10 09:22:32 1.lock
-rw-r--r-- 1 doll user  25 2022-10-10 09:22:32 molpro.rc
-rw-r--r-- 1 doll user 200 2022-10-10 09:22:32 sext.xyz

a?:
total 0
drwxr-xr-x 2 doll user 50 2022-10-10 09:22:33 16634613613130276360

a?/16634613613130276360:
total 8
-rw-r--r-- 1 doll user 227 2022-10-10 09:22:33 1.stderr
-rw-r--r-- 1 doll user  91 2022-10-10 09:22:33 1.stdout

a*:
total 0

```

So the files were rsync-ed to /SCR1/doll/a2/16634613613130276360 , and the calculation was run in

/SCR1/doll/a?/16634613613130276360

Sometimes I have this problem with backends such as withstar  , withquestionmark . For a backend without special characters,
it works reproducibly.

It is vaguely related to  https://github.com/molpro/sjef/issues/59   . One could work around this by having
extra ' ' , but this depends on the shell which we do not know.

**Comment by pjknowles** [comment]
This is understandable because now commands (both local and remote) are placed in a shell environment, whereas rsync does its own thing for expanding special characters or not.  It's complicated by the fact that the behaviour varies across the different versions of rsync currently typically installed. Probably the most robust fix is to police the choice of remote cache file name, and disallow special characters. But probably space has to be allowed if possible.

**Comment by klauspdoll** [comment]
Yes, this is also what I believe is best.
