### ISSUE TITLE
Shell()() should be able to launch local asynchronous jobs on Windows

### ISSUE THREAD

**Issue by pjknowles** [molpro/sjef#238]
Needs the windows command equivalence of /bin/sh '&', with capturing of job number.

**Comment by nick-wilson** [comment]
Currently Molpro keeps running if Jupyter kernel is shut down and Jupyter Notebook is stopped.
However Molpro is killed if the cmd window which originally launched Jupyter is closed.

If Jupyter is launched from MSYS2 then Molpro keeps running but for some reason you cannot relaunch MSYS2:
```Error: Could not fork child process: There are no available terminals (-1).```

**Comment by nick-wilson** [comment]
If JupyterLab is launched from the Anaconda Navigator in Windows then Molpro keeps running when Jupyter & Navigator are closed.
