### ISSUE TITLE
Implement push rsync in Windows

### ISSUE THREAD

**Issue by pjknowles** [molpro/sjef#239]

**Comment by nick-wilson** [comment]
Following works from a windows cmd.exe
```
/msys64/usr/bin/rsync --rsh=/usr/bin/ssh -av /c/Users/nick/source/ nickw@pjkmarat.chemy.cf.ac.uk:target/
```
rsync needs to use the ssh from inside MSYS2.
The directory names will probably need to be translated as well.

**Comment by pjknowles** [comment]
Yes that works for me too

**Comment by pjknowles** [comment]
Also seems to work with just `rsync` if you set `%PATH%`. At the moment, sjef issues `rsync` with no configurable absolute path, and relies on `Shell()` to find it. Maybe that can be used without modification just by setting the environment?
