### ISSUE TITLE
backend with blank, special characters : File/Copy

### ISSUE THREAD

**Issue by pjknowles** [molpro/sjef#62]
In GitLab by @klauspdoll on Jul 25, 2022, 08:28

`File/Copy` or `File/Save As` from the GUI calls:

`int sjef_project_copy(const char* project, const char* destination_filename, int keep_hash, int keep_run_directories)`

which calls

```
bool Project::copy(const std::filesystem::path& destination_filename, bool force, bool keep_hash, bool slave,
                   int keep_run_directories) {
```

which calls:

`  dp.clean(true, true, false, keep_run_directories);`

which calls:

`void Project::clean(bool oldOutput, bool output, bool unused, int keep_run_directories) {`

which calls:

`    run_delete(*run_list().rbegin());`

And ultimately, we have in:

`void Project::run_delete(int run)`

```
  if (m_backend != "localhost" and m_backend != "local")
    remote_server_run(std::string{"rm -rf "} + m_backends.at(m_backend).cache + filename().string() + "/run/" +
                      std::to_string(run) + "." + m_project_suffix);
```

The command to erase on the remove machine is similar to the one of issue #65 

`rm -rf cache/filename/and-so-on`

I expect that e.g. a blank in the name of the cache such as cache="/SCR/a /SRC/b" will cause similar problems.

**Comment by pjknowles** [comment]
With https://github.com/molpro/sjef/pull/193 the backend cache is no longer referenced in copying the project. Is there a remaining problem that this issue represents?

**Comment by pjknowles** [comment]
@klauspdoll please close if there's nothing left to do.

**Comment by klauspdoll** [comment]
Yes, this looks very good now.

`void Project::run_delete`

does not have to erase on the remote machine, but only locally with

`fs::remove_all(run_directory(run));`

Then this issue can be closed. (I think I can't close it)
